@staticUrl = http://localhost:3000/
@apiUrl = http://localhost:3000/api/v1/

### Static
### main page 
GET {{staticUrl}}

### event
GET {{staticUrl}}event/1

###
GET {{staticUrl}}admin

### API Gets
### menu
GET {{apiUrl}}menu

### menu with id
GET {{apiUrl}}menu/6744df739404ef80fa4344f5

### events
GET {{apiUrl}}events

### events with id
GET {{apiUrl}}events/6744ea279404ef80fa434512

### API Posts
###
POST {{apiUrl}}menu

###
POST {{apiUrl}}events